import { Const_Images } from "../Constants";
const JsonData = {
  records: [
    {
      id: 0,
      city: "Kolkata",
      category_type: "Marriage Catering Services",
      caterer_name: "Prajapati Event & Catering",
      desc: "Established in the year 2015, Prajapati Event And Catering in HOwrah HO, Howrah is a top player in the category Caterers in the Howrah. This well-known establishment acts as a one-stop destination servicing customers both local and from other parts of Howrah. Over the course of its journey, this business has established a firm foothold in it’s industry. The belief that customer satisfaction is as important as their products and services, have helped this establishment garner a vast base of customers, which continues to grow by the day. This business employs individuals that are dedicated towards their respective roles and put in a lot of effort to achieve the common vision and larger goals of the company.In the near future, this business aims to expand its line of products and services and cater to a larger client base. In Howrah, this establishment occupies a prominent location in HOwrah HO. It is an effortless task in commuting to this establishment as there are various modes of transport readily available. It is at , Near Ac Market, which makes it easy for first-time visitors in locating this establishment. It is known to provide top service in the following categories: Caterers, Stage Decorators, Flower Decorators, Birthday Party Decorators, Balloon Decorators, Car Decorators, Mandap Decorators, Decorators.",
      price: "550/plate",
      image: Const_Images.PRAJAPATI,
    },
    {
      id: 1,
      city: "Kolkata",
      category_type: "Marriage Catering Services",
      caterer_name: "Royal Cook Caterer",
      desc: "Royal Cook Caterer is a Trusted Quality Caterer for many Generations appreciated by all and has perfected the art and science of menu planning, professional service, and, most of all",
      price: "650/plate",
      image: Const_Images.ROYAL,
    },
    {
      id: 2,
      city: "Kolkata",
      category_type: "Marriage Catering Services",
      caterer_name: "La Fiesta Catering Service",
      desc: "Welcome to the best catering service in Kolkata. La Fiesta Catering is a few years old Catering Company constituted by a group of experienced professionals with a vision of amplifying extraordinary culinary skills across ceremonies and other corporate occasions with captivating hospitality.With a remarkable team of experts, we deliver the most competent service in terms of cooking and management and are most efficient in treating a mass. Our chefs having served in the Taj Bengal possess supreme knowledge regarding this business, following which we have catered to numerous big occasions successfully and acclaimed recognition in town. We are known for our highest quality food in a cost-effective package. Indian, Continental, Chinese or Mexican; La Fiesta Caterers are skilled in any sort of cuisine. ",
      price: "1000/plate",
      image: Const_Images.LA_FIESTA,
    },
    {
      id: 3,
      city: "Kolkata",
      category_type: "Marriage Catering Services",
      caterer_name: "Zenith Caterer",
      desc: "Established in the year 2017, Zenith Caterer in Paschim Putiary, Kolkata is a top player in the category Caterers in the Kolkata. This well-known establishment acts as a one-stop destination servicing customers both local and from other parts of Kolkata. Over the course of its journey, this business has established a firm foothold in it’s industry. The belief that customer satisfaction is as important as their products and services, have helped this establishment garner a vast base of customers, which continues to grow by the day. This business employs individuals that are dedicated towards their respective roles and put in a lot of effort to achieve the common vision and larger goals of the company. In the near future, this business aims to expand its line of products and services and cater to a larger client base. In Kolkata, this establishment occupies a prominent location in Paschim Putiary. It is an effortless task in commuting to this establishment as there are various modes of transport readily available. It is at Raja Rammohan Roy Road, Near Metro Park, which makes it easy for first-time visitors in locating this establishment. It is known to provide top service in the following categories: Caterers, Caterers For Wedding, Caterers For Birthday Parties, Bengali Caterers, Caterers (Upto 100 Persons), Caterers (Upto 500 Persons), Caterers (Upto 300 Persons), Caterers (Upto 200 Persons).",
      price: "650/plate",
      image: Const_Images.ZENITH,
    },
    {
      id: 4,
      city: "Kolkata",
      category_type: "Marriage Catering Services",
      caterer_name: "Raju Caterer",
      desc: "Established in the year 1988, Raju Caterer in Kankurgachi, Kolkata is a top player in the category Caterers in the Kolkata. This well-known establishment acts as a one-stop destination servicing customers both local and from other parts of Kolkata. Over the course of its journey, this business has established a firm foothold in it’s industry. The belief that customer satisfaction is as important as their products and services, have helped this establishment garner a vast base of customers, which continues to grow by the day. This business employs individuals that are dedicated towards their respective roles and put in a lot of effort to achieve the common vision and larger goals of the company. In the near future, this business aims to expand its line of products and services and cater to a larger client base. In Kolkata, this establishment occupies a prominent location in Kankurgachi. It is an effortless task in commuting to this establishment as there are various modes of transport readily available. It is at 17 BAGMARI LANE,B.R.S.10, NEAR MANICKTALA FIRE STATION BAGMARI, which makes it easy for first-time visitors in locating this establishment. It is known to provide top service in the following categories: Caterers, Caterers For Wedding, Caterers For Birthday Parties, Veg Caterers (Upto 50 Persons), Veg Caterers, Veg Caterers (Upto 300 Persons), Veg Caterers (Upto 250 Persons), Veg Caterers (Upto 200 Persons).",
      price: "400/plate",
      image: Const_Images.RAJU,
    },
    {
      id: 5,
      city: "Kolkata",
      category_type: "Marriage Catering Services",
      caterer_name: "Shomvranto Catering Service",
      desc: "Shomvranto Caterer, one of the most popular & reputed caterers in Kolkata, based on our clients’ reviews. We create unique menus for every celebration. A team of trusted and professional food experts are here to help you. Your happiness is our top priority. Shomvranto catering gives your customer a memorable experience with its creative menu, lip smacking taste, and several unique options like paan, mocktail counter and live ice creame counter. Shomvranto catering services strive to be your catering partner whether you are hosting wedding party, social event, or a corporate event. We can also help you with birthday parties and other little events where you want personal touch and attention to the detail so that you can truly enjoy the time with your family and friends.",
      price: "350/plate",
      image: Const_Images.SHOMVRANTO,
    },
    {
      id: 6,
      city: "Delhi",
      category_type: "Marriage Catering Services",
      caterer_name: "Chawla Caterer Pvt Ltd",
      desc: "Established in the year 2000, Chawla Caterers Pvt Ltd in DLF City Phase 3, Gurgaon, Delhi is a top player in the category of Caterers in the Gurgaon, Delhi. This well-known establishment acts as a one-stop destination servicing customers both local and from other parts of Gurgaon, Delhi. Over the course of its journey, this business has established a firm foothold in its industry. The belief that customer satisfaction is as important as their products and services has helped this establishment garner a vast base of customers, which continues to grow by the day. This business employs individuals that are dedicated to their respective roles and put in a lot of effort to achieve the common vision and larger goals of the company. In the near future, this business aims to expand its line of products and services and cater to a larger client base. In Gurgaon, Delhi, this establishment occupies a prominent location in DLF City Phase 3. It is an effortless task in commuting to this establishment as there are various modes of transport readily available. It is, Near DLF City Phase 3 Metro Station, which makes it easy for first-time visitors in locating this establishment. It is known to provide top service in the following categories: Caterers, Tent houses, Wedding Planners, Decorators, Party Decorators, Event Organisers For Weddings, Tent Decorators, and Caterers For Birthday Parties.",
      price: "450/plate",
      image: Const_Images.CHAWLA,
    },
    {
      id: 7,
      city: "Delhi",
      category_type: "Marriage Catering Services",
      caterer_name: "VIPS Catering",
      desc: "Established in the year 2013, VIPS Catering in Mithapur-Badarpur, Delhi is a top player in the category Italian Caterers in the Delhi. This well-known establishment acts as a one-stop destination servicing customers both local and from other parts of Delhi. Over the course of its journey, this business has established a firm foothold in it’s industry. The belief that customer satisfaction is as important as their products and services, have helped this establishment garner a vast base of customers, which continues to grow by the day. This business employs individuals that are dedicated towards their respective roles and put in a lot of effort to achieve the common vision and larger goals of the company. In the near future, this business aims to expand its line of products and services and cater to a larger client base. In Delhi, this establishment occupies a prominent location in Mithapur-Badarpur. It is an effortless task in commuting to this establishment as there are various modes of transport readily available. It is at Tanki Road, 2nd Floor Aggarwal Sweat, which makes it easy for first-time visitors in locating this establishment. It is known to provide top service in the following categories: Italian Caterers, Caterers, Mocktail Caterers, Caterers For Wedding (Upto 10000 Persons), Caterers (Upto 500 Persons), Caterers (Upto 1000 Persons), Caterers (Upto 250 Persons), Caterers For Wedding (Upto 500 Persons).",
      price: "500/plate",
      image: Const_Images.VIPS,
    },
    {
      id: 8,
      city: "Delhi",
      category_type: "Marriage Catering Services",
      caterer_name: "Mangalam Caterer",
      desc: "Established in the year 2010, Mangalam Caterers in Beta 1-Greater, Noida, Delhi is a top player in the category Caterers in the Noida, Delhi. This well-known establishment acts as a one-stop destination servicing customers both local and from other parts of Noida, Delhi. Over the course of its journey, this business has established a firm foothold in it’s industry. The belief that customer satisfaction is as important as their products and services, have helped this establishment garner a vast base of customers, which continues to grow by the day. This business employs individuals that are dedicated towards their respective roles and put in a lot of effort to achieve the common vision and larger goals of the company. In the near future, this business aims to expand its line of products and services and cater to a larger client base. In Noida, Delhi, this establishment occupies a prominent location in Beta 1-Greater. It is an effortless task in commuting to this establishment as there are various modes of transport readily available. It is at , Near Reliance Fresh, A Block, which makes it easy for first-time visitors in locating this establishment. It is known to provide top service in the following categories: Caterers, Caterers For Birthday Parties, Caterers For Wedding, Caterers For Parties, Caterers For Office, Caterers For Kitty Party, Caterers For Events, Caterers (Upto 75 Persons).",
      price: "400/plate",
      image: Const_Images.MANAGALAM,
    },
    {
      id: 9,
      city: "Delhi",
      category_type: "Marriage Catering Services",
      caterer_name: "Karachi Caterer",
      desc: "Established in the year 1955, Karachi Caterers in Gol Market, Delhi is a top player in the category Caterers For Wedding in the Delhi. This well-known establishment acts as a one-stop destination servicing customers both local and from other parts of Delhi. Over the course of its journey, this business has established a firm foothold in it’s industry. The belief that customer satisfaction is as important as their products and services, have helped this establishment garner a vast base of customers, which continues to grow by the day. This business employs individuals that are dedicated towards their respective roles and put in a lot of effort to achieve the common vision and larger goals of the company. In the near future, this business aims to expand its line of products and services and cater to a larger client base. In Delhi, this establishment occupies a prominent location in Gol Market. It is an effortless task in commuting to this establishment as there are various modes of transport readily available. It is at , Near Nirulas, which makes it easy for first-time visitors in locating this establishment. It is known to provide top service in the following categories: Caterers For Wedding, Caterers, Veg Caterers, Non Veg Caterers, Caterers For Chaat, Caterers For Wedding (Upto 500 Persons), Caterers (Upto 250 Persons), Caterers (Upto 1000 Persons).",
      price: "500/plate",
      image: Const_Images.KARACHI,
    },
    {
      id: 10,
      city: "Delhi",
      category_type: "Marriage Catering Services",
      caterer_name: "STW Caterers",
      desc: "Established in the year 2009, Stw Caterers in Rithala, Delhi is a top player in the category Caterers in the Delhi. This well-known establishment acts as a one-stop destination servicing customers both local and from other parts of Delhi. Over the course of its journey, this business has established a firm foothold in it’s industry. The belief that customer satisfaction is as important as their products and services, have helped this establishment garner a vast base of customers, which continues to grow by the day. This business employs individuals that are dedicated towards their respective roles and put in a lot of effort to achieve the common vision and larger goals of the company. In the near future, this business aims to expand its line of products and services and cater to a larger client base. In Delhi, this establishment occupies a prominent location in Rithala. It is an effortless task in commuting to this establishment as there are various modes of transport readily available. It is at Rithala Gaon, Near 990 Bus Stand, which makes it easy for first-time visitors in locating this establishment. It is known to provide top service in the following categories: Caterers, Caterers For Wedding (Upto 1000 Persons), Caterers For Wedding, Caterers For Parties, Caterers For Office, Caterers For Birthday Parties (Upto 50 Persons), Caterers For Wedding (Upto 500 Persons), Caterers For Birthday Parties.",
      price: "350/plate",
      image: Const_Images.STW,
    },
    {
      id: 11,
      city: "Delhi",
      category_type: "Marriage Catering Services",
      caterer_name: "Royal Spoon Caterers",
      desc: "Royal Spoon Caterers are one the best Caterer in Noida & Greater Noida. It is working since 2011 and has a long list of satisfied clients.The Team of Royal Spoon Caterer is the right blend of Expert Chefs & Experienced Operational Managers. The Chefs are continuously working on the quality & taste of Dishes, whereas the operational managers are striving to give the best services to the guests.Royal Spoon caterers had worked in Buddha International Circuit & India Expo Mart at various events like Formula One racings, International Bike Festival, TATA Truck Races, IHGF, Print Pack, Auto Expo, and the list is not exhaustive. We have a long association with Amity University.We are exclusively working for Amity University, Greater Noida Campus since 2014, for their catering needs. Royal Spoon Caterers has associated with so many event companies to provide catering services in mega-events.The specialization of the Royal Spoon Caterers is that we are open for any type of catering whether it is for a small gathering (starting from 30 Guests), medium gathering (100-250 Guests), or large gathering ( More than 250 to 2000 Guests), we have all the expertise for it.We also do catering for all budgets. Do tell us your budget, we will give you the best in that given budget.We also do VVIPs catering for the small number of guests for their private parties.",
      price: "1400/plate",
      image: Const_Images.ROYAL_SPOON
    },
    {
      id: 12,
      city: "Mumbai",
      category_type: "Marriage Catering Services",
      caterer_name: "Sai Caterers",
      desc: "Established in the year 1998, Sai Caterers in Chembur East, Mumbai is a top player in the category Caterers in the Mumbai. This well-known establishment acts as a one-stop destination servicing customers both local and from other parts of Mumbai. Over the course of its journey, this business has established a firm foothold in it’s industry. The belief that customer satisfaction is as important as their products and services, have helped this establishment garner a vast base of customers, which continues to grow by the day. This business employs individuals that are dedicated towards their respective roles and put in a lot of effort to achieve the common vision and larger goals of the company. In the near future, this business aims to expand its line of products and services and cater to a larger client base. In Mumbai, this establishment occupies a prominent location in Chembur East. It is an effortless task in commuting to this establishment as there are various modes of transport readily available. It is at , Opposite HT Colony, which makes it easy for first-time visitors in locating this establishment. It is known to provide top service in the following categories: Caterers, Caterers For Wedding (Upto 2000 Persons), Mexican Caterers (Upto 1000 Persons), Continental Caterers (Upto 1000 Persons), Caterers For Birthday Parties (Upto 500 Persons), Caterers For Birthday Parties (Upto 250 Persons), Caterers For Parties (Upto 2000 Persons), Caterers For Wedding (Upto 1500 Persons).",
      price: "250/plate",
      image: Const_Images.SAI,
    },
    {
      id: 13,
      city: "Mumbai",
      category_type: "Marriage Catering Services",
      caterer_name: "Anuj Catering",
      desc: "Are you or your friends organizing a big and long event like a corporate or wedding party? That requires taking care of the obvious need to eat, among many other things. Anuj Catering can arrange the catering service which includes transporting the utensils, preparing the meals, serving them and cleaning. Aside from that, such feature as food delivery is offered here.",
      price: "250/plate",
      image: Const_Images.ANUJ,
    },
    {
      id: 14,
      city: "Mumbai",
      category_type: "Marriage Catering Services",
      caterer_name: "Jay Catering Service",
      desc: "Jay Catering Services is based in Wadala, Mumbai and offers catering services for all wedding functions. This professional team is committed to provide their guests with a grand feast which they wish to host for their guests. This team has professional chefs who know how to make an ordinary dish turn into an extraordinary one. This multidisciplinary team of professionals allows the company to match the requirements of different wedding functions. Reach out to them for catering services for any of your wedding event, be it the ring ceremony or wedding ceremony.",
      price: "300/plate",
      image: Const_Images.JAY,
    },
    {
      id: 15,
      city: "Mumbai",
      category_type: "Marriage Catering Services",
      caterer_name: "Bombay Essence Caterers",
      desc: "Established in the year 2014, Bombay Essence Caterers in Borivali East, Mumbai is a top player in the category Veg Caterers in the Mumbai. This well-known establishment acts as a one-stop destination servicing customers both local and from other parts of Mumbai. Over the course of its journey, this business has established a firm foothold in it’s industry. The belief that customer satisfaction is as important as their products and services, have helped this establishment garner a vast base of customers, which continues to grow by the day. This business employs individuals that are dedicated towards their respective roles and put in a lot of effort to achieve the common vision and larger goals of the company. In the near future, this business aims to expand its line of products and services and cater to a larger client base. In Mumbai, this establishment occupies a prominent location in Borivali East. It is an effortless task in commuting to this establishment as there are various modes of transport readily available. It is at Western Express Highway, Near National Park, which makes it easy for first-time visitors in locating this establishment. It is known to provide top service in the following categories: Veg Caterers, Caterers, Caterers For Wedding, Maharashtrian Caterers, Gujarati Caterers, Punjabi Caterers, Marwari Caterers, Caterers For Function.",
      price: "450/plate",
      image: Const_Images.BOMBAY_ESSENCE1,
    },
    {
      id: 16,
      city: "Mumbai",
      category_type: "Marriage Catering Services",
      caterer_name: "Purnima Caterers",
      desc: "PURNIMA CATERERS is a premium wedding catering services in MUMBAI. We deliver premium food and catering services for events to our clients by concentrating on Decorations, Presentation, Taste, and Variety. Our regard to detail, our focus on providing innovative solutions for our clients, and our thoughtful process differentiate us from others in our industry.As a catering services for wedding, we extend a full range of catering arrangements and provide experienced and event organizers who will ensure that your event is arranged to maximize your success and executed meticulously.At PURNIMA CATERERS, we recognize that your big day is one of the most significant days you will ever experience. We have a considerable collection of contemporary and original wedding menus, wonderful decors, trusted styling partners and all-inclusive wedding packages. With our special catering, Various displays, live stations & a wide range of cuisine, you are SPOILT for choices.So, whether it is your Mehndi Function, Ring Ceremony, Haldi Function, Wedding Ceremony or Wedding reception, our clear, modern cuisine is thoughtfully composed to tantalise taste buds & emotions with flavour, texture & timeless presentation.",
      price: "550/plate",
      image: Const_Images.PURNIMA,
    },
    {
      id: 17,
      city: "Mumbai",
      category_type: "Marriage Catering Services",
      caterer_name: "Le Kitchen Caterers",
      desc: "Located in Mumbai, Le Kitchen is a premium catering service with lots to offer for their clients. They are in the business of providing flavoursome delights that elevate an event into heavenly bliss. With their popular motto, food for soul, they try to achieve soulful excellence with professional, classy and efficient service for all types of events, including weddings.",
      price: "1000/plate",
      image: Const_Images.LEKITCHEN,
    },
    {
      id: 18,
      city: "Chennai",
      category_type: "Marriage Catering Services",
      caterer_name: "Seemantham Catering",
      desc: "This seemantham catering menu list includes the best south Indian item, As the best catering service provider in Chennai city.",
      price: "350/plate",
      image: Const_Images.SEEMANTHAM,
    },
    {
      id: 19,
      city: "Chennai",
      category_type: "Marriage Catering Services",
      caterer_name: "RK Caterer",
      desc: "Also listed in Caterers, Veg Caterers, Biryani Caterers, Caterers (Upto 50 Persons), Brahmin Food Caterers, etc. R K Caterers in Nungambakkam is one of the most trustworthy names in the field. They have received a 4.9 rating from their customers. To make the transactional experience hassle-free for customers, they accept multiple modes of payment such as Cash, Master Card, Visa Card, Debit Cards, Cheques, American Express Card, and Credit Card. The best time to contact them is anytime between Open 24 Hrs – Open 24 Hrs.",
      price: "450/plate",
      image: Const_Images.RK_CATERER,
    },
    {
      id: 20,
      city: "Chennai",
      category_type: "Marriage Catering Services",
      caterer_name: "Sona Caterers",
      desc: "Sona Caterers in Anna Nagar West, Chennai is a reliable name in the industry as they aim to deliver the best experience to their customers. This has helped them build up a loyal customer base. They started their journey in 2000 and ever since, they have ensured that the customer remains at the center of their business operations and philosophy. As they are located in a favorable neighborhood, exactly at No 3 B 11 Sneham Apartments 3rd Floor, Opposite Lucas TVS, Park Road, Anna Nagar West-600101 near Opposite Lucas TVS, it is easy to locate Sona Caterers on the map. For any kind of assistance or questions, it is best to contact them directly during their business hours.",
      price: "550/plate",
      image: Const_Images.SONA_CATERER,
    },
    {
      id: 21,
      city: "Chennai",
      category_type: "Marriage Catering Services",
      caterer_name: "Sri Moogambikai Caterer",
      desc: "Original Sri Moogambikai Marriage Catering Service in K K Nagar, Chennai is a reliable name in the industry as they aim to deliver the best experience to their customers. This has helped them build up a loyal customer base. They started their journey in 1990 and ever since, they have ensured that the customer remains at the center of their business operations and philosophy. As they are located in a favorable neighborhood, exactly at No 964 A, Near Ayyapan Temple, Laksmanan Swamy Street, K K Nagar-600078 near Ayyapan Temple, it is easy to locate Original Sri Moogambikai Marriage Catering Service on the map. For any kind of assistance or questions, it is best to contact them directly during their business hours.",
      price: "350/plate",
      image: Const_Images.MOOGAMBIKA,
    },
    {
      id: 22,
      city: "Chennai",
      category_type: "Marriage Catering Services",
      caterer_name: "Iyenagar Caterers",
      desc: "Iyengar Catering in Villivakkam, Chennai is a reliable name in the industry as they aim to deliver the best experience to their customers. This has helped them build up a loyal customer base. They started their journey in and ever since they have ensured that the customer remains at the center of their business operations and philosophy. As they are located in a favorable neighborhood, exactly at No 92a/18 Trisool Chopra Flats, South Mada Street, Villivakam, Villivakkam-600049, it is easy to locate Iyengar Catering on the map. For any kind of assistance or questions, it is best to contact them directly during their business hours.",
      price: "400/plate",
      image: Const_Images.IYENAGAR,
    },
  ],
};
export default JsonData;
